name: jtex
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: test template.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install -g jtex
      - run: jtex check
